import { Evento, Perfil } from "../type";

export const dadosPerfil: Perfil = {
  nome: "Marcos Patricio Flamenguista",
  imagem: "",
  icone: "person",
};

export const dadosEventos: Evento[] = [
  {
    data: new Date("2023-05-26T19:00Z"),
    previsto: new Date("2023-05-26T19:00Z"),
    realizado: null,
    duracao: null,
    tolerancia: null,
    titulo: "Vacina da Covid",
    subtitulo: "Posto de saúde do bairro",
    destaque: "",
    categoria: {
      nome: "Vacina",
      icone: "vaccines",
    },
    status: "atrasado",
    criticidade: "media",
    acao: true,
  },
  {
    data: new Date("2022-12-26T18:10Z"),
    previsto: new Date("2022-12-26T18:10Z"),
    realizado: null,
    duracao: null,
    tolerancia: null,
    titulo: "Vacina da gripe",
    subtitulo: "Posto de saúde do bairro",
    destaque: "",
    categoria: {
      nome: "Vacina",
      icone: "vaccines",
    },
    status: "atrasado",
    criticidade: "media",
    acao: false,
  },
  {
    data: new Date("2023-05-02T17:00Z"),
    previsto: new Date("2023-05-02T17:00Z"),
    realizado: null,
    duracao: null,
    tolerancia: null,
    titulo: "Evento atual ",
    subtitulo: "02/05",
    destaque: "",
    categoria: {
      nome: "Ligação",
      icone: "call",
    },
    status: "planejado",
    criticidade: "baixa",
    acao: false,
  },
  {
    data: new Date("2023-05-02T19:00Z"),
    previsto: new Date("2023-05-02T19:00Z"),
    realizado: null,
    duracao: null,
    tolerancia: null,
    titulo: "próximo evento",
    subtitulo: "02/05",
    destaque: "Estava passando mal",
    categoria: {
      nome: "Cardiologista",
      icone: "cardiology",
    },
    status: "atrasado",
    criticidade: "alta",
    acao: false,
  },
  {
    data: new Date("2023-04-19T11:00Z"),
    previsto: new Date("2023-04-19T11:00Z"),
    realizado: null,
    duracao: null,
    tolerancia: null,
    titulo: "Consulta Clinico geral",
    subtitulo: "Posto de saúde do bairro",
    destaque: "Estava passando mal",
    categoria: {
      nome: "Cardiologista",
      icone: "cardiology",
    },
    status: "cancelado",
    criticidade: "media",
    acao: false,
  },
  {
    data: new Date("2023-04-19T10:00Z"),
    previsto: new Date("2023-04-19T10:00Z"),
    realizado: null,
    duracao: null,
    tolerancia: null,
    titulo: "Consulta",
    subtitulo: "Posto de saúde",
    destaque: "",
    categoria: {
      nome: "Tele consulta",
      icone: "call",
    },
    status: "realizado",
    criticidade: "alta",
    acao: false,
  },
  {
    data: new Date("2023-04-19T18:00Z"),
    previsto: new Date("2023-04-19T18:00Z"),
    realizado: null,
    duracao: null,
    tolerancia: null,
    titulo: "Consulta cardiologista",
    subtitulo: "Posto de saúde do bairro",
    destaque: "",
    categoria: {
      nome: "Cardiologista",
      icone: "cardiology",
    },
    status: "adiado",
    criticidade: "alta",
    acao: false,
  },
  {
    data: new Date("2023-04-20T12:30Z"),
    previsto: new Date("2023-04-20T12:30Z"),
    realizado: null,
    duracao: null,
    tolerancia: null,
    titulo: "Vacina da gripe",
    subtitulo: "Posto de saúde do bairro",
    destaque: "",
    categoria: {
      nome: "Vacina",
      icone: "vaccines",
    },
    status: "atrasado",
    criticidade: "media",
    acao: false,
  },
];
